### ISSUE TITLE
use

### ISSUE THREAD

**Issue by HalaSalameh** [mimacom/mmc-breadcrumbs#1]
how should i exactly use this? 
because i tried installing it and using it but it keeps saying there is no module

**Comment by mirko-lazarevic** [comment]
hello @HalaSalameh, unfortunately I didn't have time to add proper documentation, but here is the quick explanation how you can use it.

Import the `MmcBreadcrumbsModule` in your root module (`app.module.ts`) 

```javascript
import { RouterModule } from '@angular/router';
import {MmcBreadcrumbsModule} from 'mmc-breadcrumbs';

@NgModule({
  imports: [
    RouterModule.forRoot(myRoutes),
    MmcBreadcrumbsModule.forRoot()
  ],  
})
export class AppModule {}
```

Place the `mmc-breadcrumbs` component, which will render the breadcrumbs, 
somewhere in your markup.

```javascript
@Component({
  selector: 'app-root',
  template: `
    <div class="container">
      <mmc-breadcrumbs></mc-breadcrumbs>
      <router-outlet></router-outlet>
    </div>`
})
export class AppComponent {}
```

Breadcrumbs links are generated based on the route configuration. If a route 
entry contains a `data.breadcrumbs` property the _breadcrumbs service_ assumes 
breadcrumbs should be created whenever this route or one its child routes are 
active.

```javascript
const myRoutes : Route[] = {
  {
    path: '',
    component: HomeComponent,
    data: {
      // Uses static text (Home)
      breadcrumbs: 'Home' 
    }
  }
```

Note: This library is forked from https://github.com/McNull/ngx-breadcrumbs, there you can find detailed explanation how you can use it. Of course, you have to adapt names

**Comment by HalaSalameh** [comment]
it worked!
thank you so much
